# .streamlit/secrets.toml
EIA_API_KEY = "ytr6gUXinTIt7k0BaowMfj1ag5RIXZTlR2zzTFsu"

[gcp_service_account]
type = "service_account"
project_id = "sipa-adv-c-silly-penguin"
private_key_id = "9b482ef7e6216b2859e15a33a9de7955ed551e1d"
private_key = """-----BEGIN PRIVATE KEY-----
MIIEvAIBADANBgkqhkiG9w0BAQEFAASC
BKYwggSiAgEAAoIBAQDEF2xij3puhIbJ
ng+FGcW3U5IqEuV3PjD2VgDfps16LAUslqBAeizm6BggtcmKFFadKCPlQZbuDcpp
lvzE3pOZdEFadhT7AKSLz+bsNIVnOsDdzfpJbOCcYIvA0CjMHyxFsb5C+21oTzfZ
iTa0lPY8AJoOCfic/u2npsPK27TLNzcFqbYHirZY4sP40UhU7Jr/Lq47l7TmieBo
jVZ7pVs1SJSPP7zmHRSPx/DlZNPypOkwaeFRaE0yJOv9u0m12vqFL1QdDpxM6+Ym
T11W5EsQ4Ws3CZhDMtiWUGei1U31xGdfZfpZ1QROg5nkaMKbvoAEAxYLru8LBkk+
CVqogmxtAgMBAAECggEAFOVZGayn85CAS4piJYEgUl+ftweR99HDBnEWQT8FbPQ1
bfG0LILId6e6cHvmuOXfb/pXzuWdJ4uFKxjZoUIFsQfUMgdcx32jSznRphCXua8n
X8uEFSB60/cu1VJpUo0s2tVszLb9yuyMK0yFrZslHTJEOGREH7jDywaInTyp6LCu
uAalvhnbZ8xdZIAIb8TNfeyF87r7FGbkIYACtbfloMGSOo0+ysvZwVNWyp5JMdkv
OIOOk5+yVz44s8sEDWnh8sylMvDLZGSeNlmdupo9Dyjs1t1cJbyev6uE2U2x/rL0
B95WaI7IsNiAEHlGlyeUJ0CUxyGZkzAQMIkhQQF2uQKBgQD9o1LFnvAxcmPfYu1k
18POQvsn7IzcriKDXDiOP2ws8vhnIa+XOYZ867ilG3reCbqlpiABDdej7v58+jTC
H0NzJHQPGTncCHumjJ+f4jt/dlSQfGE23V2UaMTQQcmEUcY91r+U1PAiR8tdmRbG
NcbVUmww7AWYgIsKYV7tbeeHBQKBgQDF6uiMG3TO+j5e1K9/5oBfLcfsiNV2GrHZ
K9BfARoE5UyTldAZpjkdx2lZAUWGucUjLKOpsa4wdoNHB7b1ZTx8/PxVwTLrKruS
4D9WzzYZrTovUAaYsMuGf0w/h3Ev3s9jpmt/aWBVPftGQa953fJ8pm/v659zmVmJ
A7YnwoT8SQKBgGSrmoLNntBBctqLTWYlLZaEh2NFRHOiuhghVmE/UxRUK7vjZupC
7tpORS9jRNU0T1zIHxPMBrcOePvp417ZQdBFu7rybEClLU7hqcmv5aWltdLTS1KX
cjkhjFyMgAuA2YpZ3hiYm+c/T7yKsrthRNYOrNqOE3qAKq+oDiF26dpxAoGAMMD9
KAZbb+EVHCcoVEljtg6BATNz4fQRe33fhoeu8SXLB1AQQ0E/MKa+vL4jclyww0lr
x5GNZ0LKc+TinPCjRebMAhPlhyivrC6xa6D/orOZca408cgbWrZhAgVLTI+GZvXH
5Ur///+UtmnX4B1cbnhReriAPum3tJjFdmXkfIECgYBjx3zijKc5qhvPZRcpEAIq
noN1X31LuClCsWc62KKjig6i/oS54U7jixAKWiOEZ+9Ta0Jl/CHn9SaajJnwCFD4
BO5ueOQpNH9u5LMov5iINrt7ifRPVNIPSV6U9YoQJ1SmDNa3qrXK3r5vsZjgYEAB
FumVQ81KxhIw4FhQcOOLag==
-----END PRIVATE KEY-----
"""
client_email = "streamlit@sipa-adv-c-silly-penguin.iam.gserviceaccount.com"
client_id = "116546695497535957900"
auth_uri = "https://accounts.google.com/o/oauth2/auth"
token_uri = "https://oauth2.googleapis.com/token"
auth_provider_x509_cert_url = "https://www.googleapis.com/oauth2/v1/certs"
client_x509_cert_url = "https://www.googleapis.com/robot/v1/metadata/x509/streamlit%40sipa-adv-c-silly-penguin.iam.gserviceaccount.com"
universe_domain = "googleapis.com"
